drop table customer, vehicle, rental, rate;
DROP VIEW VrentalInfo;

Create table CUSTOMER(
CustID INT NOT NULL AUTO_INCREMENT ,
Name VARCHAR(30) NOT NULL,
Phone VARCHAR(15),
primary key(CustID)
);

CREATE TABLE VEHICLE(
VehicleID VARCHAR(17) NOT NULL,
Description VARCHAR(30) NOT NULL,
Year INT NOT NULL,
Type INT NOT NULL,
Category INT NOT NULL,
PRIMARY KEY(VehicleID)
);

Create table RENTAL(
CustID INT not null,
VehicleID VARCHAR(17) NOT NULL,
StartDate DATE NOT NULL,
OrderDate DATE NOT NULL,
RentalType INT,
Qty INT,
ReturnDate DATE NOT NULL,
TotalAmount FLOAT NOT NULL,
PaymentDate CHAR(10),

FOREIGN KEY(CustID) REFERENCES CUSTOMER(CustID),
FOREIGN KEY(VehicleID) REFERENCES VEHICLE(VehicleID)
);



CREATE TABLE RATE(
Type INT NOT NULL,
Category INT NOT NULL,
Weekly DECIMAL(10,2) NOT NULL,
Daily DECIMAL(10,2) NOT NULL,
PRIMARY KEY(Type,Category)
);

LOAD DATA INFILE 'c:/ProgramData/MySQL/MySQL Server 8.0/Uploads/CUSTOMER.CSV'
INTO TABLE CUSTOMER
COLUMNS TERMINATED BY ','
LINES TERMINATED BY '\n'
IGNORE 1 LINES
;

LOAD DATA INFILE 'c:/ProgramData/MySQL/MySQL Server 8.0/Uploads/VEHICLE.CSV'
INTO TABLE VEHICLE
COLUMNS TERMINATED BY ','
LINES TERMINATED BY '\n'
IGNORE 1 LINES
;

LOAD DATA INFILE 'c:/ProgramData/MySQL/MySQL Server 8.0/Uploads/RATE.CSV'
INTO TABLE RATE
COLUMNS TERMINATED BY ','
LINES TERMINATED BY '\n'
IGNORE 1 LINES
;

LOAD DATA INFILE 'c:/ProgramData/MySQL/MySQL Server 8.0/Uploads/RENTAL.CSV'
INTO TABLE RENTAL
COLUMNS TERMINATED BY ','
LINES TERMINATED BY '\n'
IGNORE 1 LINES
;



